@startuml
object Main

object Car{
    -String make
    -String model
    -int year
    -String bodyStyle
    -Driver driver

    +Car(String make, String model, int year, String bodyStyle)
    +Driver getDriver()
    +setDriver(Driver driver)
    +String toString()
}

object Driver{
    -String name
    -int age

    +Driver(String name, int age)
    +String toString()
}

Car *-- Driver
Main *-- Car

Main : {static}+Main()

@enduml
